In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("integration/df_final.csv")
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'integration/df_final.csv'

In [ ]:
np.random.seed(42)

In [ ]:
df_simulated = df.copy()

In [ ]:
# Simulate individual-level income: add noise to state-level Median_Income
df_simulated["individual_income"] = df_simulated["Median_Income"] + np.random.normal(0, 10000, size=len(df_simulated))
df_simulated.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,...,Bachelors,Masters,Doctorate,Rural,Urban,Total,Urban_Pct,Rural_Pct,State_Type,individual_income
0,9046,1,67.0,0,1,1,Private,Urban,228.69,36.6,...,584999,345966,49857,2,7,9,77.777778,22.222222,Mixed,93396.141530
1,31112,1,80.0,0,1,1,Private,Rural,105.92,32.5,...,958365,391150,71956,51,44,95,46.315789,53.684211,Rural,63871.356988
2,60182,0,49.0,0,0,1,Private,Urban,171.23,34.4,...,725469,345957,54737,20,26,46,56.521739,43.478261,Mixed,70591.885381
3,1665,0,79.0,1,0,1,Self-employed,Rural,174.12,24.0,...,525044,218915,35332,27,37,64,57.812500,42.187500,Mixed,70646.298564
4,56669,1,81.0,0,0,1,Private,Urban,186.21,29.0,...,151894,81198,14956,1,2,3,66.666667,33.333333,Mixed,79832.466253

In [ ]:
# Simulate individual-level education score based on state-level education counts
edu_weights = {"HS_Grad": 1, "Bachelors": 2, "Masters": 3, "Doctorate": 4}
df_simulated["education_score"] = (
    df_simulated["HS_Grad"] * edu_weights["HS_Grad"] +
    df_simulated["Bachelors"] * edu_weights["Bachelors"] +
    df_simulated["Masters"] * edu_weights["Masters"] +
    df_simulated["Doctorate"] * edu_weights["Doctorate"]
)

In [ ]:
# Normalize the education score to a 0–100 scale for interpretability
edu_min = df_simulated["education_score"].min()
edu_max = df_simulated["education_score"].max()
df_simulated["education_score"] = 100 * (df_simulated["education_score"] - edu_min) / (edu_max - edu_min)

In [ ]:
df_simulated[["stroke", "age", "hypertension", "heart_disease", "bmi", "avg_glucose_level", "Median_Income", "individual_income", "education_score", "Urban_Pct", "State_Type"
]].head()

,stroke,age,hypertension,heart_disease,bmi,avg_glucose_level,Median_Income,individual_income,education_score,Urban_Pct,State_Type
0,1,67.0,0,1,36.6,228.69,88429,93396.141530,9.842136,77.777778,Mixed
1,1,80.0,0,1,32.5,105.92,65254,63871.356988,16.088449,46.315789,Rural
2,1,49.0,0,0,34.4,171.23,64115,70591.885381,12.036045,56.521739,Mixed
3,1,79.0,1,0,24.0,174.12,55416,70646.298564,8.762857,57.812500,Mixed
4,1,81.0,0,0,29.0,186.21,82174,79832.466253,1.615077,66.666667,Mixed

In [ ]:
df_simulated.to_csv("final_project/integration/df_final_simulated.csv", index=False)